version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # Algolia
  ALGOLIA_APP_ID: app_id
  ALGOLIA_API_KEY: api_key
  ALGOLIA_INDEX_NAME: index_name
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Chroma
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # DuckDB
  DUCKDB_DATABASE: database
  DUCKDB_SCHEMA: main
  # Google
  # GOOGLE_SERVICE_ACC_KEY:
    # type: service_account
    # project_id: project-id
    # private_key_id: key-id
    # private_key: "-----BEGIN PRIVATE KEY-----\nyour_private_key\n-----END_PRIVATE_KEY"
    # client_email: your_service_account_email
    # auth_uri: "https://accounts.google.com/o/oauth2/auth"
    # token_uri: "https://accounts.google.com/o/oauth2/token"
    # auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    # client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/your_service_account_email"
  # GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/path/to/your/service/account/key.json"
#   GOOGLE_SERVICE_ACC_KEY:  
#     type: service_account
#     project_id: mage-project-74715
#     private_key_id: 3584748e4a256f9f327deee4e9e2a1a3af2a60f3
#     private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCM/QqcfN3HNEdH\nTW78iibNTH+4VdLe7K+pF3fUGuOnt4V93XYW0rsI3DaR6fXoSkn+dWPjfUcbFS9J\nfxQ8E3sgF05r09ern7+pN/pc6DWIcAOrjNk6bv1w7H3UF9txaj55WQg7/lV8AGgR\n+JyRGlJSkjGz4M6qlZIyK97dgrJU2XrvhAlDxgZdkhhvKs0UaOa5fRgDUSviHAKv\ngRHQD7wnLs99UD0tMwZfqsZqTufWLhHbM8pTBWT7Ai0ahJCgOJYMnnwPj19y4IOc\naNAjvHk68zZDL5yBBrQg90oN15Gh/9DWWXRtuD9TM+AFOwX56/mUvjh2vboZixWA\nbWdaAXcRAgMBAAECggEAGnFoQNbzkqXlu4QUraVspyMyrjxcj0aVoLF/3kaHzcBQ\nN33mpNuzzDLfQkk+/6kVTTYvvK5VvIjh5FdDEIx30ppEcVlbcTtGS4LuAGhmB/e4\nXH/Pi1PfUYNtiy7JT/GFE6Xk8zmdx2LdIge+t8FX0NhOHaZrpJdmguXzCBk4AM09\nKGtSKItadD09gbmZoiDPRhxNmab4kjkaImAyw5teS6oqxvfdOBtkCs/3c5rYGkGg\noVpd24qT2HGKMOo4WdZdPkoY3T4MH+qGKmu/o2h6dg/wx/cNaYD45R0VvfYf9eYJ\nQIsOlxkMJGLX/jLUH/onCsC1RbV+6EQ1pna1d2qvpQKBgQDBdHV7eyodGHm64U3K\n49HeUblVLdufItmxX/wrEdE0lC3AhvpLWWrSfqWuVOGAxoJuEg3uLIm8lBLqCip0\n52cF1aQ2CCeFD56fxjhMrvlYRld3B3ee+wKVH4naWA46aJaCdMhMVSUOxHckyc2a\nMbFs36E6c4zvgCkmcqth6gfFRQKBgQC6kiDdRci8cW/daA9kV7RH+ePvMjtBcXDO\ncIc3JlWw85hgyI4ZxiYDwQeL0VZ6aZ9irlajN2wDj7NbBriq6qiFqFDvxarLM04t\nG2zlFvcq65z5TloW2RI/xmjSLINxGe5zLO+eq9GeZoKdwCwAgFAFmCyV/m0RRSE5\n4vzH4sfpXQKBgEXWcA8K0JI+YrunWHkVM49pu1lXu8BASYxyFUvLG9Y6ZCXr1HHd\nLuYcmF1OATaG81EfLW49H+A3KHjbAKbBXvzJOoXS/clYcTBG085DIHrQsgSjani3\nLyB8iTyMq15EoYko9aIw3rbtEAH05Ed1BxNBzCeYzVks0C40GVC4tuNtAoGAdLLs\nrZt12TFXWHU7k3cshAzxnu+bku7DMc2/NibbWMi12mv4PnTr2FNIRhOV9RHWKWKF\nPKhw/rVG6bwFjJsk+B11KtVIZLvdvWc3MQCxb/5afLKetUXoHU4cyMIhIYCn3xEP\nfP9aKatTLhtDKrkX1Lf/w36WeEP2aX/qv5jBlN0CgYAgtBg01GQuWH6wd83h+swz\n8wMWAh2amndAEtb8KWt6aVsy48lb9mhKX7P7Cl466pLWxvca5wKBAsF6zlnRlkTP\ng4pqEYpqznG3MjsuFFigb4DDU4MI4wB7+Pd4cl/43HtQ+zTRp3osxeSN0p8xZVue\nbGnNgnXi/hIFI+bcSynvjg==\n-----END PRIVATE KEY-----\n"
#     client_email: mage-zoomcamp@mage-project-74715.iam.gserviceaccount.com
#     # client_id: 116821442844904235828
#     auth_uri: "https://accounts.google.com/o/oauth2/auth"
#     token_uri: "https://oauth2.googleapis.com/token"
#     auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
#     client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/mage-zoomcamp%40mage-project-74715.iam.gserviceaccount.com"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/src/mage-project-74715-3584748e4a25.json"
  # GOOGLE_LOCATION: US # Optional
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # Pinot
  PINOT_HOST: hostname
  PINOT_PASSWORD: password
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: user
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # Qdrant
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
  # Weaviate
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INSTANCE_API_KEY: YOUR-WEAVIATE-API-KEY
  WEAVIATE_INFERENCE_API_KEY: YOUR-OPENAI-API-KEY
  WEAVIATE_COLLECTION: collectionn_name

dev:
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: "{{ env_var('POSTGRES_DBNAME') }}"
  POSTGRES_SCHEMA: "{{ env_var('POSTGRES_SCHEMA') }}"
  POSTGRES_USER: "{{ env_var('POSTGRES_USER') }}"
  POSTGRES_PASSWORD: "{{ env_var('POSTGRES_PASSWORD') }}"
  POSTGRES_HOST: "{{ env_var('POSTGRES_HOST') }}"
  POSTGRES_PORT: "{{ env_var('POSTGRES_PORT') }}"
